---
  - name: Install some nice packages
    apk:
      name: "{{ item }}"
      state: present
    loop: 
      - gnome-mines
      - mesa-dri-gallium
      - mesa-va-gallium
      - intel-media-driver