---
  - name: Install dev packages
    apk:
      name: "{{ item }}"
      state: present
    loop:
      - go
      - neovim
      - git
      - code-oss
      - php
      - podman
      - podman-compose
  - name: Configure podman
    shell: |
      rc-update add cgroups
      rc-service cgroups start
      modprobe tun
      echo tun >>/etc/modules
      echo {{ USERNAME }}:100000:65536 >/etc/subuid
      echo {{ USERNAME }}:100000:65536 >/etc/subgid
